package Animation;

public class BigdrePaintProgram extends javax.swing.JFrame {

    public BigdrePaintProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolButtonGroup = new javax.swing.ButtonGroup();
        shapeButtonGroup = new javax.swing.ButtonGroup();
        colorButtonGroup = new javax.swing.ButtonGroup();
        paintPanel = new javax.swing.JPanel();
        mousePosition = new javax.swing.JLabel();
        paintMenuBar = new javax.swing.JMenuBar();
        toolMenu = new javax.swing.JMenu();
        drawMenuItem = new javax.swing.JRadioButtonMenuItem();
        fillMenuItem = new javax.swing.JRadioButtonMenuItem();
        shapeMenu = new javax.swing.JMenu();
        pointMenuItem = new javax.swing.JRadioButtonMenuItem();
        lineMenuItem = new javax.swing.JRadioButtonMenuItem();
        ovalMenuItem = new javax.swing.JRadioButtonMenuItem();
        rectangleMenuItem = new javax.swing.JRadioButtonMenuItem();
        triangleMenuItem = new javax.swing.JRadioButtonMenuItem();
        colorMenu = new javax.swing.JMenu();
        blackMenuItem = new javax.swing.JRadioButtonMenuItem();
        redMenuItem = new javax.swing.JRadioButtonMenuItem();
        greenMenuItem = new javax.swing.JRadioButtonMenuItem();
        blueMenuItem = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bigdre's Paint Program");
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(816, 683));

        paintPanel.setBackground(new java.awt.Color(255, 255, 255));
        paintPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        paintPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paintPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paintPanelMousePressed(evt);
            }
        });
        paintPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                paintPanelMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                paintPanelMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout paintPanelLayout = new javax.swing.GroupLayout(paintPanel);
        paintPanel.setLayout(paintPanelLayout);
        paintPanelLayout.setHorizontalGroup(
            paintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paintPanelLayout.setVerticalGroup(
            paintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        mousePosition.setText("000, 000");

        toolMenu.setText("Tool");

        toolButtonGroup.add(drawMenuItem);
        drawMenuItem.setSelected(true);
        drawMenuItem.setText("Draw");
        toolMenu.add(drawMenuItem);

        toolButtonGroup.add(fillMenuItem);
        fillMenuItem.setText("Fill");
        toolMenu.add(fillMenuItem);

        paintMenuBar.add(toolMenu);

        shapeMenu.setText("Shape");

        shapeButtonGroup.add(pointMenuItem);
        pointMenuItem.setSelected(true);
        pointMenuItem.setText("Point");
        shapeMenu.add(pointMenuItem);

        shapeButtonGroup.add(lineMenuItem);
        lineMenuItem.setText("Line");
        shapeMenu.add(lineMenuItem);

        shapeButtonGroup.add(ovalMenuItem);
        ovalMenuItem.setText("Oval");
        shapeMenu.add(ovalMenuItem);

        shapeButtonGroup.add(rectangleMenuItem);
        rectangleMenuItem.setText("Rectangle");
        shapeMenu.add(rectangleMenuItem);

        shapeButtonGroup.add(triangleMenuItem);
        triangleMenuItem.setText("Triangle");
        shapeMenu.add(triangleMenuItem);

        paintMenuBar.add(shapeMenu);

        colorMenu.setText("Color");

        colorButtonGroup.add(blackMenuItem);
        blackMenuItem.setSelected(true);
        blackMenuItem.setText("Black");
        colorMenu.add(blackMenuItem);

        colorButtonGroup.add(redMenuItem);
        redMenuItem.setForeground(new java.awt.Color(255, 0, 0));
        redMenuItem.setText("Red");
        colorMenu.add(redMenuItem);

        colorButtonGroup.add(greenMenuItem);
        greenMenuItem.setForeground(new java.awt.Color(0, 255, 0));
        greenMenuItem.setText("Green");
        colorMenu.add(greenMenuItem);

        colorButtonGroup.add(blueMenuItem);
        blueMenuItem.setForeground(new java.awt.Color(0, 0, 255));
        blueMenuItem.setText("Blue");
        colorMenu.add(blueMenuItem);

        paintMenuBar.add(colorMenu);

        setJMenuBar(paintMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paintPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 357, Short.MAX_VALUE)
                .addComponent(mousePosition))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paintPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mousePosition))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void paintPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintPanelMouseExited
        mousePosition.setText("N/A");
    }//GEN-LAST:event_paintPanelMouseExited

    private void paintPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintPanelMouseMoved
        int x = evt.getX();
        int y = evt.getY();
        mousePosition.setText(x + ", " + y);
    }//GEN-LAST:event_paintPanelMouseMoved

    private void paintPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintPanelMouseDragged
        java.awt.Point currentPoint = evt.getPoint();
        java.awt.Graphics g = paintPanel.getGraphics();
        if (lineMenuItem.isSelected()) {
            shape = new Shape(Shape.LINE, mousePoint, currentPoint);
        }
        else if (ovalMenuItem.isSelected()) {
            shape = new Shape(Shape.OVAL, mousePoint, currentPoint);
        }
        else if (rectangleMenuItem.isSelected()) {
            shape = new Shape(Shape.RECTANGLE, mousePoint, currentPoint);
        }
        if (shape != null) {
            shape.drawShape(g);
        }
    }//GEN-LAST:event_paintPanelMouseDragged

    private void paintPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paintPanelMousePressed
        mousePoint = evt.getPoint();
    }//GEN-LAST:event_paintPanelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BigdrePaintProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BigdrePaintProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BigdrePaintProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BigdrePaintProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BigdrePaintProgram().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem blackMenuItem;
    private javax.swing.JRadioButtonMenuItem blueMenuItem;
    private javax.swing.ButtonGroup colorButtonGroup;
    private javax.swing.JMenu colorMenu;
    private javax.swing.JRadioButtonMenuItem drawMenuItem;
    private javax.swing.JRadioButtonMenuItem fillMenuItem;
    private javax.swing.JRadioButtonMenuItem greenMenuItem;
    private javax.swing.JRadioButtonMenuItem lineMenuItem;
    private javax.swing.JLabel mousePosition;
    private javax.swing.JRadioButtonMenuItem ovalMenuItem;
    private javax.swing.JMenuBar paintMenuBar;
    private javax.swing.JPanel paintPanel;
    private java.awt.Point mousePoint;
    private Shape shape;
    private javax.swing.JRadioButtonMenuItem pointMenuItem;
    private javax.swing.JRadioButtonMenuItem rectangleMenuItem;
    private javax.swing.JRadioButtonMenuItem redMenuItem;
    private javax.swing.ButtonGroup shapeButtonGroup;
    private javax.swing.JMenu shapeMenu;
    private javax.swing.ButtonGroup toolButtonGroup;
    private javax.swing.JMenu toolMenu;
    private javax.swing.JRadioButtonMenuItem triangleMenuItem;
    // End of variables declaration//GEN-END:variables
}
